a = int(input('Digite um número: '))
print('A tabuada de {} é:'.format(a))
print('{}x1={}'.format(a, a*1))
print('{}x2={}'.format(a, a*2))
print('{}x3={}'.format(a, a*3))
print('{}x4={}'.format(a, a*4))
print('{}x5={}'.format(a, a*5))
print('{}x6={}'.format(a, a*6))
print('{}x7={}'.format(a, a*7))
print('{}x8={}'.format(a, a*8))
print('{}x9={}'.format(a, a*9))
print('{}x10={}'.format(a, a*10))
